### ISSUE TITLE
Python - plot window appears, but is blank white

### ISSUE THREAD

**Issue by Fishified** [jorishey1234/tractrac#1]
Great package, thanks. When I try to run your tutorials output appears in the console and a matplotlib window appears. But it remains blank. I get this error statement after running python tractrac.py -p 1 -a from the python folder:

![image](https://user-images.githubusercontent.com/12990745/57568722-4c6f0900-73b9-11e9-9a0f-0110321aebea.png)

**Comment by jorishey1234** [comment]
It can come from the backend your matplotlib is using. Try forcing tkagg by adding a matplotlibrc file insidein the TracTrac Python folder with inside :

backend : TKagg
